### ISSUE TITLE
Removing field from form object, then setting as child of another form, adds field back

### ISSUE THREAD

**Issue by bishopb** [kristijanhusak/laravel4-form-builder#1]
Essential form:

```
$child = Form::create(...);
$child->remove('removed_field');

$parent = Form::create(...);
$parent->add('child', 'form', [ 'class' => $child ]);

form($parent); // yields a form containing removed_field 
```

Looks like ChildFormType::createChildren() line 27 in the `rebuildForm()` call is adding the fields back based on the original form specification.  The docs do seem to be "class" oriented, but as objects are accepted, I'm expecting the object state to remain.

**Comment by kristijanhusak** [comment]
Yes, you are right. I'll look into it, and let you know when it's fixed. Thanks for reporting.

**Comment by kristijanhusak** [comment]
I fixed it. Do a composer update. If it's ok, please close this issue.

**Comment by bishopb** [comment]
Confirmed, thanks!
