### ISSUE TITLE
Show all errors, not just first.

### ISSUE THREAD

**Issue by bishopb** [kristijanhusak/laravel4-form-builder#4]
I've noticed that the error messages in templates call `->first()`, but I think a more generic approach using `->all()` would support broader use.  For example:

``` php
@if ($errors->has())
   <div class='errors'>
   @foreach ($errors->all() as $error)
      <div class='error'>{{ $error }}</div>
   @endforeach
  </div>
@endif
```

Consider password validation.  When a password fails to satisfy policy, there may be multiple messages, like "Password must contain at least one number" and "Password must contain at least one letter".  All of these should be shown.

This can be solved by imploding all messages into the first.  (What I'm doing now, actually.)  Alternatively, this could be handled with custom templates.  Both of these feel like hacks, though.

**Comment by bishopb** [comment]
As a separate feature, it'd be nice to have the ability to specify the format to `->all()`, [as documented](http://laravel.com/docs/4.2/validation#working-with-error-messages):

``` php
@foreach ($errors->all($this->errorFormat) as $error)
```

**Comment by kristijanhusak** [comment]
That sounds like a good idea. Will fix it soon. Thanks.

**Comment by kristijanhusak** [comment]
I added it, it prints in in this way:

```
foreach ($errors->get('fieldname') as $error) {
   <div {{ $options[errorAttrs]] }}>{{ $error }}</div>
}
```

Please test it and see if it's ok.

**Comment by bishopb** [comment]
Checking on it now, thanks.

I noticed an odd version number increase, just FYI:

```
  - Removing kris/laravel4-form-builder (1.3.5)
  - Installing kris/laravel4-form-builder (1.3.70)
```

**Comment by bishopb** [comment]
Confirmed, it works, thanks!
I didn't get it with 1.3.70, so looks like a new tag will be needed.

**Comment by kristijanhusak** [comment]
Strange, you should get 1.4.0

https://packagist.org/packages/kris/laravel4-form-builder

Try doing another composer update.

**Comment by bishopb** [comment]
Whoops, yeah, I was tilde-locked to 1.3 series!
