### ISSUE TITLE
id and name attributes not matching in collection types

### ISSUE THREAD

**Issue by lordjancso** [kristijanhusak/laravel4-form-builder#5]
see title

**Comment by kristijanhusak** [comment]
I think this also should be fixed with the latest commit. Test it out and close this if it's fine.

**Comment by lordjancso** [comment]
@kristijanhusak 
Last commit doesn't solve this issue.

**Comment by kristijanhusak** [comment]
@lordjancso 
I did some fixing, but not sure if it's working. I would really appreciate if You could pull in dev version and see if it works out for you, and then i'll publish a release fix.

**Comment by lordjancso** [comment]
Its working. You can release changes! Thank you!

**Comment by kristijanhusak** [comment]
@lordjancso 
Released, you can do a composer update.
