### ISSUE TITLE
access prototype from view?

### ISSUE THREAD

**Issue by lordjancso** [kristijanhusak/laravel4-form-builder#7]
I would like to add prototype-s to a data attribute in all collection view.
Is this possible to access prototype string in views/collection.php?

**Comment by kristijanhusak** [comment]
Adding it directly to the `views/collection.php` is not possible with default `collection` type. You can create custom collection field type, extend default one and pass the prototype in view. Something like this:

``` php

class CustomCollectionType extends CollectionType {

    public function render(array $options = [], $showLabel = true, $showField = true, $showError = true)
    {
        $options['prototype'] = $this->prototype;

        return parent::render($options, $showLabel, $showField, $showError);
    }
```

**Comment by lordjancso** [comment]
Thank you. I will do this way.
