### ISSUE TITLE
prototype name in nested forms

### ISSUE THREAD

**Issue by lordjancso** [kristijanhusak/laravel4-form-builder#8]
Is possible to inherit parents prototype name into childrens prototype in multiple nested form collections?
If I have users with multiple addresses, and address can have multiple cars. Car form prototype looks like this:

```
<div class="form-group"  >
  <label for="addresses[0][cars][__NAME__][brand]" class="control-label" for="timezone">Brand</label>
  <input class="form-control" name="addresses[0][cars][__NAME__][brand]" type="text" id="addresses[0][cars][__NAME__][brand]">
</div>  
```

This would be better this way:

```
<div class="form-group"  >
  <label for="addresses[__ADDRESS_NAME__][cars][__CAR_NAME__][brand]" class="control-label" for="timezone">Brand</label>
  <input class="form-control" name="addresses[__ADDRESS_NAME__][cars][__CAR_NAME__][brand]" type="text" id="addresses[__ADDRESS_NAME__][cars][__CAR_NAME__][brand]">
</div>  
```

**Comment by kristijanhusak** [comment]
Yeah, I agree it's better. Didn't think of that. Will work on it during this week, because i'ts a bigger issue. Thanks for reporting.

**Comment by lordjancso** [comment]
Thank you! I will keep an eye on your project!

**Comment by kristijanhusak** [comment]
@lordjancso 
I fixed this, finally got some time to analyze it properly. At this moment it's only on dev branch, because i'm planning to release 1.6. If you can, pull the dev version and test it out.

**Comment by lordjancso** [comment]
Cool, I will test it soon. Should I close this now?

**Comment by kristijanhusak** [comment]
Close it after you test it and it works fine.
