### ISSUE TITLE
Display errors for collections

### ISSUE THREAD

**Issue by lordjancso** [kristijanhusak/laravel4-form-builder#9]
When you using collections in your form and you got error for a collection element, errors bag looks like this:

```
object(Illuminate\Support\ViewErrorBag)[125]
  protected 'bags' => 
    array (size=1)
      'default' => 
        object(Illuminate\Support\MessageBag)[126]
          protected 'messages' => 
            array (size=1)
              'maximum' => 
                array (size=1)
                  0 => string 'The maximum must be a number.' (length=29)
          protected 'format' => string ':message' (length=8)
```

In this example there is a recipient collection which has minimum and maximum fields. Now I typed string into the second collection elements maximum field, but the error 'Max must be a number' will show for every maximum fields in this collection.

**Comment by kristijanhusak** [comment]
I'm not sure if Laravel's validator is able to handle that type of validation. Structure of `messages` looks same as for normal field.

```
protected $messages = ['maximum' => ['The maximum must be a number']];
```

I think that validator should return message with key `maximum.0` for the first collection item, `maximum.1` for 2nd, and so on, to properly show these errors.

**Comment by lordjancso** [comment]
Hmm yeah, you're almost right.
The main problem is if I have error in the second collection, error bag looks like as I paste above.
So there should be the error in maximum.1 instead of maximum.0.
Now I really don't know which element have error or not.

**Comment by kristijanhusak** [comment]
Yes, in that case it should be `maximum.1`. You need to create custom validator for this, which will return proper messages.

**Comment by lordjancso** [comment]
What do you mean? Could you be more specific?
I don't see how custom validator solve this problem.
In this case I have 3 elements and and 1 error message, but I don't know that error message is for which element. This is a little bit confusing. :)

**Comment by kristijanhusak** [comment]
Laravel's validator is not able to validate array of data. Try something like this http://ericlbarnes.com/laravel-array-validation/

**Comment by lordjancso** [comment]
This article is for Laravel 5. I guess I can not use this in Laravel 4... :(

**Comment by kristijanhusak** [comment]
I think it's same for Laravel 4, Nothing big changed in Validator from version 4 to 5.

**Comment by kristijanhusak** [comment]
I'm closing this, since it's not form builder issue.
